# Site settings
title: un pitone a san luca
email: enrico.giampieri@unibo.it
description: "my blog for ranting about decision theory, statistics, programming in python and other random stuff"
baseurl: ""
url: "http://EnricoGiampieri.github.com"

# Build settings
markdown: kramdown
permalink: pretty

baseurl: "http://enricogiampieri.github.io/"

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#
analytics :
provider : google
google :
tracking_id : 'UA-52517157-1'
getclicky :
site_id :