# Site settings
title: un pitone a san luca
email: enrico.giampieri@unibo.it
description: "my blog for ranting about decision theory, statistics, programming in python and other random stuff"
baseurl: ""
url: "http://EnricoGiampieri.github.com"

# Build settings
markdown: kramdown
permalink: pretty

baseurl: "http://enricogiampieri.github.io/"