# Site settings
title: God save the variance!
email: enrico.giampieri@unibo.it
description: "my blog for ranting about decision theory, statistics and stuff"
baseurl: ""
url: "http://EnricoGiampieri.github.com"

# Build settings
markdown: kramdown
permalink: pretty
